apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: zabbix-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
        tier: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:ubuntu-4.0.16
          ports:
          - containerPort: 10051
            name: server
          env:
          - name: DB_SERVER_HOST
            value: zabbix-db
          - name: MYSQL_DATABASE
            value: zabbix_proxy
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            value: zabbix
