apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-proxy
  labels:
    app: zabbix
    tier: zabbix-proxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: zabbix-proxy
        app: zabbix
        tier: zabbix-proxy
    spec:
      containers:
        - name: zabbix-proxy
          image: zabbix/zabbix-proxy-sqlite3:ubuntu-4.0.16
          ports:
          - containerPort: 10051
            name: server
          env:
          - name: ZBX_HOSTNAME
            value: "{{ .Release.Name }}"
          - name: ZBX_SERVER_HOST
            value: zabbix-server
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            value: zabbix
          resources:  
            requests:
              cpu: 4
              memory: 8Gi