apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-proxy
  labels:
    app: zabbix
    tier: zabbix-proxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: zabbix-proxy
        app: zabbix
        tier: zabbix-proxy
    spec:
      containers:
        - name: zabbix-proxy
          image: zabbix/zabbix-proxy-mysql:ubuntu-4.0.16
          env:
          - name: ZBX_SERVER_HOST
            value: zabbix-server
          - name: DB_SERVER_HOST
            value: zabbix-db
          - name: MYSQL_DATABASE
            value: zabbix
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            value: zabbix
          requests:
            cpu: 4
            memory: 8Gi