apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy
  labels:
    app: zabbix
    tier: proxy
spec:
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-proxy
      - port: 10050
      targetPort: 10050
      name: zabbix-proxy
  selector:
    name: zabbix-proxy  
