apiVersion: v1
kind: Service
metadata:
  name: {{ include "zbx.fullname" . }}
  labels:
    {{- include "zbx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ include "zbx.fullname" . }}-web    