apiVersion: v1
kind: Service
metadata:
  name: {{ include "zbx.fullname" . }}-jv-gt
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  - port: 10052
    targetPort: 10052
    name: {{ include "zbx.fullname" . }}-jmx
  selector:
    name: {{ include "zbx.fullname" . }}-jv-gt
