apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ include "zbx.fullname" . }}-server
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: server
    environment: dev
  namespace: zbx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ include "zbx.fullname" . }}-server
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ include "zbx.fullname" . }}-server
          image: "zabbix/zabbix-server-mysql:{{ .Values.image.tagzb }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: {{ include "zbx.fullname" . }}-trapper
          readinessProbe:
            tcpSocket:
              port: {{ include "zbx.fullname" . }}-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ include "zbx.fullname" . }}-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
          - name: DB_SERVER_HOST
            value: {{ .Values.serverdb }}
          - name: MYSQL_USER
            value: "zabbix"
          - name: MYSQL_PASSWORD
            value: "zabbix"
          - name: MYSQL_ROOT_PASSWORD
            value: "zabbix"
          - name: MYSQL_DATABASE
            value: "zabbix"
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_STARTJAVAPOLLERS
            value: "5"
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "true"
          - name: ZBX_STARTPROXYPOLLERS
            value: "5"
          - name: ZBX_PROXYCONFIGFREQUENCY
            value: "60"
          volumeMounts:
          - name: {{ include "zbx.fullname" . }}-zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: true
        - name: {{ include "zbx.fullname" . }}-zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:ubuntu-3.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 162
            protocol: UDP
            name: {{ include "zbx.fullname" . }}-snmp-trap
          volumeMounts:
          - name: {{ include "zbx.fullname" . }}-zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: false
      volumes:
       - hostPath:
          path: /zabbix/
         name: {{ include "zbx.fullname" . }}-zabbix-db-storage
