apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ include "zbx.fullname" . }}-web
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: zabbix-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ include "zbx.fullname" . }}-web
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ include "zbx.fullname" . }}-web
          image: "zabbix/zabbix-web-apache-mysql:{{ .Values.image.tagzb }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: {{ include "zbx.fullname" . }}-web-http
          env:
          - name: DB_SERVER_HOST
            value: "10.110.27.111"
          - name: MYSQL_USER
            value: "zabbix"
          - name: MYSQL_PASSWORD
            value: "zabbix"
