apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ include "zabbix.fullname" . }}-zabbix-proxy-sqlite3
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: proxy
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ include "zabbix.fullname" . }}-zabbix-proxy-sqlite3
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ include "zabbix.fullname" . }}-zabbix-proxy-sqlite3
          image: "zabbix/zabbix-proxy-sqlite3:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          env:
          - name: ZBX_HOSTNAME
            value: "zabbix-proxy"
          - name: ZBX_PROXYMODE
            value: "0"
          - name: ZBX_SERVER_HOST
            value: "zabbix-zabbix-server"
