apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "phpmyadmin.fullname" . }}
spec:
  rules:
  - host: {{ .Values.service.hostname }}
    http:
      paths:
      - backend:
          serviceName: "{{ template "phpmyadmin.fullname" . }}"
          servicePort: 80
        path: /
