apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "phpmyadmin.fullname" . }}
spec:
  rules:
  - host: "phpmyadmin.casa"
    http:
      paths:
      - backend:
          serviceName: demo
          servicePort: 80
        path: /
