image:
  registry: docker.io
  repository: phpmyadmin/phpmyadmin
  tag: 5.0.1
  ## Specify a imagePullPolicy
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

db:

  port: 3306

  bundleTestDB: false

  ## Whether to enable SSL for the connection between phpMyAdmin and the MySQL server to secure the connection
  ##
  enableSsl: false
  ssl:
    ## Client key file when using SSL
    ##
    clientKey: |-
    ## Client certificate file when using SSL
    ##
    clientCertificate: |-
    ## CA file when using SSL
    ##
    caCertificate: |-
    ## List of allowable ciphers for connections when using SSL
    ##
    # ciphers:
    ## Enable SSL certificate validation
    ##
    verify: true
  host: "-"
  mysqlUser: "-"
  mysqlrootPassword: "-"   

ingress:

  enabled: true

  certManager: false

  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /
    
  labels: {}
  path: /
  hosts:
    - chart-example.local
  tls: []


probesEnabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podLabels: {}

podAnnotations: {}

metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-9-r148
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"

