kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "zabbix.fullname" . }}-startup-scripts
  labels:
    app: {{ template "zabbix.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  entrypoint.sh: |
{{ .Files.Get "files/entrypoint.sh" | indent 4 }}
  functions.sh: |
{{ .Files.Get "files/functions.sh" | indent 4 }}
