apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zabbix.fullname" . }}
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zabbix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zabbix.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zabbix.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: zabbix-web
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: zabbix/zabbix-web-apache-mysql:centos-3.4
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB_SERVER_HOST
            value: {{ .Values.serverdb }}
          - name: MYSQL_USER
            value: "zabbix"
          - name: MYSQL_PASSWORD
            value: "zabbix"
          - name: ZBX_SERVER_HOST
            value: zabbix-server
          ports:
            - name: service
              containerPort: 80
              protocol: TCP
            - name: zabbix
              containerPort: 80
              protocol: TCP 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}     
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
