apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    tier: zabbix-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-db
        app: zabbix
        tier: zabbix-db
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:ubuntu-3.0.29
          ports:
          - containerPort: 10051
            name: server
          env:
          - name: DB_SERVER_HOST
            value: zabbix-db
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            value: zabbix     
