apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    tier: zabbix-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-db
        app: zabbix
        tier: zabbix-db
    spec:
      containers:
        - name: zabbix-db
          image: mysql:8.0.19
          ports:
          - containerPort: 3306
            name: mariadb
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: zabbix
          - name: MYSQL_DATABASE
            value: zabbix
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            value: zabbix
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: zabbix-db-storage
        emptyDir:
          medium: Memory