apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: zabbix-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
        tier: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: "zabbix/zabbix-server-mysql:{{ .Values.image.tag }}"
          ports:
          - containerPort: 10051
            name: server
          env:
          - name: DB_SERVER_HOST
            value: {{ .Values.serverdb }}
          - name: MYSQL_USER
            value: "zabbix"
          - name: MYSQL_PASSWORD
            value: "zabbix"
        - name: zabbix-agent
          image: "zabbix/zabbix-agent:{{ .Values.image.tag }}"
          ports:
          - containerPort: 10050
            name: agent
          env:
          - name: ZBX_SERVER_HOST
            value: zabbix-server
          - name: ZBX_HOSTNAME
            value: zabbix-server   

