apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "zabbix.fullname" . }}
spec:
  rules:
  - host: "zabbix-toolstc.t-systems.es"
    http:
      paths:
      - backend:
          serviceName: {{ template "zabbix.fullname" . }}
          servicePort: 80
        path: /
        