apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
spec:
  type: Nodeport
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-server
      protocol: TCP
    - port: 10050
      targetPort: 10050
      name: zabbix-server0
      protocol: TCP
  externalIPs:
    - {{ .Values.externalIP }}
  selector:
    name: zabbix-server 
