apiVersion: v1
kind: Service
metadata:
  name: {{ include "zabbix.fullname" . }}
  labels:
    app: {{ include "zabbix.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.service.percona.headless }}
  clusterIP: None
  {{- end }}
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: {{ include "zabbix.fullname" . }}
    release: "{{ .Release.Name }}"
