apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
    tier: server
spec:
  ports:
    - port: 10050
      targetPort: 10050
      name: zabbix-agent
  selector:
    name: zabbix-agent