apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    tier: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: zabbix-db
  selector:
    name: zabbix-db    