apiVersion: v1
kind: Service
metadata:
  name: {{ include "zabbix.fullname" . }}-zabbix-server
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
spec:
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-trapper
  selector:
    name: zabbix-server
  clusterIP: none  
  externalIPs:
  - "{{ .Values.externalIP }}"  