apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: zabbix-agent
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: agent
spec:
  selector:
      matchLabels:
        name: zabbix-agent
  updateStrategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 1
  template:
    metadata:
      labels:
        name: zabbix-agent
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: zabbix-agent
          image: "zabbix/zabbix-agent:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 10050
            name: zabbix-agent
          env:
          - name: ZBX_SERVER_HOST
            value: {{ .Values.externalIP }}
          - name: ZBX_PASSIVE_ALLOW
            value: "true"
          - name: ZBX_STARTAGENTS
            value: "3"
          - name: ZBX_TIMEOUT
            value: "10"
          securityContext:
            privileged: true