apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pandora-fms.fullname" . }}
  labels:
    {{- include "pandora-fms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pandora-fms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pandora-fms.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pandora-fms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:

        - name: "pandorafms-mysql"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "pandorafms/pandorafms-mysql:6"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mysqlRootPass }}
          - name:  MYSQL_DATABASE
            value: {{ .Values.mysqlDB }}
          - name: MYSQL_USER
            value: {{ .Values.mysqlUser }}
          - name: MSQL_PASSWORD
            values: {{ .Values.m
            ysqlPass}}   

        - name: "Pandora-server"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: pandorafms/pandorafms-server:6
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PANDORA_DB_HOST
            value: ""
          - name: PANDORA_DB_USER
            value: ""  
          - name: PANDORA_DB_PASSWORD
            value: ""

        - name: "Pandora-console"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: pandorafms/pandorafms-console:6
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PANDORA_DB_HOST
            value: ""
          - name: PANDORA_DB_USER
            value: ""
          - name: PANDORA_DB_PASSWORD
            values: ""
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
