apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ include "zb-k8s.fullname" . }}-zabbix-java-gateway
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: java
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ include "zb-k8s.fullname" . }}-zabbix-java-gateway
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ include "zb-k8s.fullname" . }}-zabbix-java-gateway
          image: "zabbix/zabbix-java-gateway:{{ .Values.image.tagzb }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 10052
            protocol: TCP
            name: {{ include "zb-k8s.fullname" . }}-zabbix-jmx
          env:
          - name: ZBX_TIMEOUT
            value: "5"
